services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env.wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.mysql
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  wordpress_data:
  mysql_data:
